spring.application.name = careercompass

# H2 Database
spring.datasource.url = jdbc:h2:mem:careercompassdb
spring.datasource.driver-class-name = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password =
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.h2.console.enabled = true

# JPA
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true

adzuna.app.id = dcf19718
adzuna.app.key = 43933adfaab8bcec9d6af319935b9043

# JSearch API (RapidAPI) — get key at rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch
jsearch.api.key = f3b23305cemsh388a7dd1431b84fp16965ajsn8aee1de7b066
